vim.keymap.set('n', '<leader>drf', dbt.run)
vim.keymap.set('n', '<leader>drp', dbt.run_all)
vim.keymap.set('n', '<leader>dtf', dbt.test)
vim.keymap.set('n', '<leader>dm', require('dbtpal.telescope').dbt_picker)
vim.keymap.set('n', '<leader>drf', dbt.run)
vim.keymap.set('n', '<leader>drp', dbt.run_all)
vim.keymap.set('n', '<leader>dtf', dbt.test)
vim.keymap.set('n', '<leader>dm', require('dbtpal.telescope').dbt_picker)
